apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
        app: server
        tier: backend
  ports:
  - targetPort: 8080
    port: 80
    protocol: TCP
    name: http
  - targetPort: 8081
    port: 443
    protocol: TCP
    name: https
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
        app: dashborad
        tier: frontend
  ports:
  - targetPort: 8080
    port: 80
    protocol: TCP
    name: http
  - targetPort: 8081
    port: 443
    protocol: TCP
    name: https